DROP TABLE IF EXISTS files;
CREATE TABLE files (
	id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
	created DATETIME DEFAULT (DATETIME(CURRENT_TIMESTAMP, 'LOCALTIME')),
	filename TEXT NOT NULL,
	arcname TEXT NOT NULL,
	type TEXT NOT NULL,
	directory TEXT NOT NULL
);
